### ISSUE TITLE
[1pt] Create app and install basic dependencies - Setup (group task)

### ISSUE THREAD

**Issue by DevKaranJ** [DevKaranJ/space-travelers-hub#24]
- Create React App.
- Install [React Redux](https://react-redux.js.org/), [Redux Logger](https://www.npmjs.com/package/redux-logger) and [React Router](https://reactrouter.com/web/guides/quick-start).

**Comment by DevKaranJ** [comment]
Hey @NoelLincoln ,

As we are a team of two, we need to make some adjustments to the code based on the project requirements. We won't be working with the Dragons data since the project specifies that it should only be included if our team has 3 members.

Here's what needs to be done:

1. **Remove Dragons Data Fetch:**
   - In the code, locate the part where we are fetching data from the Dragons API (https://api.spacexdata.com/v4/dragons).
   - Remove the entire section responsible for fetching and storing Dragons data in the Redux store.

2. **Update the Project Requirements:**
   - Make sure that any references to Dragons data are removed from the project requirements and documentation.

3. **Linters and Code Consistency:**
   - Ensure that our code follows proper linting and coding standards to maintain consistency. You can refer to our linters configuration (if not already set up) here: [Linters Config](https://github.com/microverseinc/linters-config/tree/master/react-redux).

4. **README File Update:**
   - Update our project's README file to reflect the changes we've made, including the removal of Dragons data and any updated project requirements. A well-documented README is essential for clear communication.

5. **Test the Application:**
   - After making these changes, ensure that the application still works correctly by fetching Rockets and Missions data as required.

Let me know if you have any questions or need further clarification on these changes. Once you've made these updates, we should be in compliance with the project requirements for a team of two members.

Thanks for your cooperation!

**Comment by NoelLincoln** [comment]
Hello @DevKaranJ , I am finishing up on the changes
